version: '3.8'

services:
  fastapi:
    build: .
    container_name: tutorial-server
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    command: nohup uvicorn main:app --host 0.0.0.0 --port 8001 --reload --workers 4 > tutorial_server.log 2>&1 &
