version: '3.8'

services:
  apache-php:
    build: .  # Add this line to use Dockerfile
    container_name: apache_php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - lamp_network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lamp_network

networks:
  lamp_network:
    driver: bridge

volumes:
  mysql_data: